#!/bin/sh
		
pkg_base=`pkg info DISense-base | head -n 1 | cut -c1-12`
if [ "$pkg_base" = "DISense-base" 2>&1 >/dev/null ]; then
	echo "DISense Base package is already installed"
else
	echo -n "Installing DISense Base package....."
	pkg install -y DISense-base 2>&1 >/dev/null
	echo "done"
fi
